from requests.machine_data_requests import MachineNetworkData, MachineState

NETWORK_DATA_DUMMY = {
        1: MachineNetworkData(id=1, group='desktop', group_member_id=1, port=11001, domain='desktop1.wisniowa.oedu.pl'),
        2: MachineNetworkData(id=2, group='desktop', group_member_id=2, port=11002, domain='desktop2.wisniowa.oedu.pl'),
        3: MachineNetworkData(id=3, group='desktop', group_member_id=3, port=11003, domain='desktop3.wisniowa.oedu.pl'),
        4: MachineNetworkData(id=4, group='desktop', group_member_id=4, port=11004, domain='desktop4.wisniowa.oedu.pl'),
        5: MachineNetworkData(id=5, group='desktop', group_member_id=5, port=11005, domain='desktop5.wisniowa.oedu.pl'),
        6: MachineNetworkData(id=6, group='desktop', group_member_id=6, port=11006, domain='desktop6.wisniowa.oedu.pl'),
        7: MachineNetworkData(id=7, group='desktop', group_member_id=7, port=11007, domain='desktop7.wisniowa.oedu.pl'),
        8: MachineNetworkData(id=8, group='desktop', group_member_id=8, port=11008, domain='desktop8.wisniowa.oedu.pl'),
        9: MachineNetworkData(id=9, group='desktop', group_member_id=9, port=11009, domain='desktop9.wisniowa.oedu.pl'),
        10: MachineNetworkData(id=10, group='desktop', group_member_id=10, port=11010, domain='desktop10.wisniowa.oedu.pl'),
        11: MachineNetworkData(id=11, group='desktop', group_member_id=11, port=11011, domain='desktop11.wisniowa.oedu.pl'),
        12: MachineNetworkData(id=12, group='desktop', group_member_id=12, port=11012, domain='desktop12.wisniowa.oedu.pl'),
        13: MachineNetworkData(id=13, group='desktop', group_member_id=13, port=11013, domain='desktop13.wisniowa.oedu.pl'),
        14: MachineNetworkData(id=14, group='desktop', group_member_id=14, port=11014, domain='desktop14.wisniowa.oedu.pl'),
        15: MachineNetworkData(id=15, group='desktop', group_member_id=15, port=11015, domain='desktop15.wisniowa.oedu.pl'),
        16: MachineNetworkData(id=16, group='desktop', group_member_id=16, port=11016, domain='desktop16.wisniowa.oedu.pl'),
        17: MachineNetworkData(id=17, group='serwer', group_member_id=1, port=12001, domain='serwer1.wisniowa.oedu.pl'),
        18: MachineNetworkData(id=18, group='serwer', group_member_id=2, port=12002, domain='serwer2.wisniowa.oedu.pl'),
        19: MachineNetworkData(id=19, group='serwer', group_member_id=3, port=12003, domain='serwer3.wisniowa.oedu.pl'),
        20: MachineNetworkData(id=20, group='serwer', group_member_id=4, port=12004, domain='serwer4.wisniowa.oedu.pl'),
        21: MachineNetworkData(id=21, group='serwer', group_member_id=5, port=12005, domain='serwer5.wisniowa.oedu.pl'),
        22: MachineNetworkData(id=22, group='serwer', group_member_id=6, port=12006, domain='serwer6.wisniowa.oedu.pl'),
        23: MachineNetworkData(id=23, group='serwer', group_member_id=7, port=12007, domain='serwer7.wisniowa.oedu.pl'),
        24: MachineNetworkData(id=24, group='serwer', group_member_id=8, port=12008, domain='serwer8.wisniowa.oedu.pl'),
        25: MachineNetworkData(id=25, group='serwer', group_member_id=9, port=12009, domain='serwer9.wisniowa.oedu.pl'),
        26: MachineNetworkData(id=26, group='serwer', group_member_id=10, port=12010, domain='serwer10.wisniowa.oedu.pl'),
        27: MachineNetworkData(id=27, group='serwer', group_member_id=11, port=12011, domain='serwer11.wisniowa.oedu.pl'),
        28: MachineNetworkData(id=28, group='serwer', group_member_id=12, port=12012, domain='serwer12.wisniowa.oedu.pl'),
        29: MachineNetworkData(id=29, group='serwer', group_member_id=13, port=12013, domain='serwer13.wisniowa.oedu.pl'),
        30: MachineNetworkData(id=30, group='serwer', group_member_id=14, port=12014, domain='serwer14.wisniowa.oedu.pl'),
        31: MachineNetworkData(id=31, group='serwer', group_member_id=15, port=12015, domain='serwer15.wisniowa.oedu.pl'),
        32: MachineNetworkData(id=32, group='serwer', group_member_id=16, port=12016, domain='serwer16.wisniowa.oedu.pl')
    }
STATE_DUMMY = {
        1: MachineState(id=1, group='desktop', group_member_id=1, active=True, cpu=84, ram_used=1913, ram_max=4096),
        2: MachineState(id=2, group='desktop', group_member_id=2, active=True, cpu=40, ram_used=1068, ram_max=4096),
        3: MachineState(id=3, group='desktop', group_member_id=3, active=False, loading=True),
        4: MachineState(id=4, group='desktop', group_member_id=4, active=False),
        5: MachineState(id=5, group='desktop', group_member_id=5, active=False),
        6: MachineState(id=6, group='desktop', group_member_id=6, active=True, cpu=97, ram_used=1194, ram_max=4096),
        7: MachineState(id=7, group='desktop', group_member_id=7, active=True, cpu=46, ram_used=2076, ram_max=4096),
        8: MachineState(id=8, group='desktop', group_member_id=8, active=False, loading=True),
        9: MachineState(id=9, group='desktop', group_member_id=9, active=True, cpu=60, ram_used=1646, ram_max=4096),
        10: MachineState(id=10, group='desktop', group_member_id=10, active=True, cpu=35, ram_used=971, ram_max=4096),
        11: MachineState(id=11, group='desktop', group_member_id=11, active=True, cpu=54, ram_used=3875, ram_max=4096),
        12: MachineState(id=12, group='desktop', group_member_id=12, active=False),
        13: MachineState(id=13, group='desktop', group_member_id=13, active=True, cpu=87, ram_used=2795, ram_max=4096),
        14: MachineState(id=14, group='desktop', group_member_id=14, active=False),
        15: MachineState(id=15, group='desktop', group_member_id=15, active=True, cpu=16, ram_used=341, ram_max=4096),
        16: MachineState(id=16, group='desktop', group_member_id=16, active=True, cpu=30, ram_used=1190, ram_max=4096),
        17: MachineState(id=17, group='serwer', group_member_id=1, active=True, cpu=22, ram_used=2813, ram_max=4096),
        18: MachineState(id=18, group='serwer', group_member_id=2, active=True, cpu=63, ram_used=2055, ram_max=4096),
        19: MachineState(id=19, group='serwer', group_member_id=3, active=False),
        20: MachineState(id=20, group='serwer', group_member_id=4, active=False),
        21: MachineState(id=21, group='serwer', group_member_id=5, active=False, loading=True),
        22: MachineState(id=22, group='serwer', group_member_id=6, active=False),
        23: MachineState(id=23, group='serwer', group_member_id=7, active=True, cpu=9, ram_used=2178, ram_max=4096),
        24: MachineState(id=24, group='serwer', group_member_id=8, active=False),
        25: MachineState(id=25, group='serwer', group_member_id=9, active=True, cpu=65, ram_used=2102, ram_max=4096),
        26: MachineState(id=26, group='serwer', group_member_id=10, active=False),
        27: MachineState(id=27, group='serwer', group_member_id=11, active=True, cpu=25, ram_used=3042, ram_max=4096),
        28: MachineState(id=28, group='serwer', group_member_id=12, active=True, cpu=46, ram_used=641, ram_max=4096),
        29: MachineState(id=29, group='serwer', group_member_id=13, active=False, loading=True),
        30: MachineState(id=30, group='serwer', group_member_id=14, active=True, cpu=78, ram_used=3617, ram_max=4096),
        31: MachineState(id=31, group='serwer', group_member_id=15, active=True, cpu=2, ram_used=1511, ram_max=4096),
        32: MachineState(id=32, group='serwer', group_member_id=16, active=True, cpu=72, ram_used=2557, ram_max=4096)
}